### ISSUE TITLE
import Z address

### ISSUE THREAD

**Issue by Pega88** [johandjoz/Material-Eleos#10]
To import a Z-address, the UI asks for the 'private key'.

However, when using the a private key generated by https://zclassicpaperwallet.com/, this does not work and gives following error:
<img width="265" alt="screen shot 2018-01-15 at 00 10 12" src="https://user-images.githubusercontent.com/1451524/34921914-b58d27f2-f988-11e7-9fae-7cb602432570.png">

when importing the spending key however, it does work (after restart).

This seems confusing for users that are asked to 'import Z private key" but actually need to use 'Z spending key'

**Comment by 11000000110000110100001101011010** [comment]
ok I change for "spending key"
