### ISSUE TITLE
app not closing decently after importing private key

### ISSUE THREAD

**Issue by Pega88** [johandjoz/Material-Eleos#9]
when importing a private key (either T or Z), the app is not terminating correctly (as restart needed after import). You cannot restart the wallet. Manually killing process zlc-cli-mac in terminal solves this, and you can restart without a problem.

This only occurs after importing a private key. Otherwise everything is fine.

tested on Mac only

**Comment by Pega88** [comment]
update: waiting a decent amount of time (+30 seconds) also solved it, however this is not a great user experience.

**Comment by 11000000110000110100001101011010** [comment]
Just wait for rescan
